name: shashety_mobile
description: Movie streaming service.
version: 3.1.6+38

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  queries: ^0.1.12
  built_value: ^6.3.0
  built_collection: ^4.1.0
  http: ^0.12.0
  incrementally_loading_listview: ^0.0.4+3
  carousel_slider: ^1.1.0
  rate_my_app: ^0.2.0+4

  # TV
  screen: ^0.0.4
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  cloud_firestore: ^0.9.0
  firebase_storage: ^2.0.0
  firebase_auth: ^0.8.0
  image_picker: ^0.5.0
  uuid: ^2.0.0
  scoped_model: ^1.0.1
  cached_network_image: ^1.0.0
  flare_flutter: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.1.3
  built_value_generator: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    # - assets/post-placeholder.png
    - assets/placeholder.png
    - assets/featured-placeholder.jpg
    - assets/flare/orb.flr
    - assets/flare/head.flr

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
