name: shashety_mobile
description: Movie streaming service.
version: 2.6.3+25

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  queries: ^0.1.12
  built_value: ^6.3.0
  built_collection: ^4.1.0
  http: ^0.12.0
  incrementally_loading_listview: ^0.0.4+3
  carousel_slider: ^1.1.0
  # flutter_appavailability: ^0.0.21
  # android_intent: ^0.3.0+1
  # url_launcher: ^5.0.2

  # tv
  video_player: ^0.7.2
  screen: ^0.0.4
  after_layout: ^1.0.7
  open_iconic_flutter: '>=0.3.0 <0.4.0'
  cloud_firestore: ^0.9.0
  firebase_storage: ^2.0.0
  firebase_auth: ^0.8.0
  image_picker: ^0.5.0
  uuid: ^1.0.3
  scoped_model: ^1.0.1
  cached_network_image: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.1.3
  built_value_generator: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'
